name: Run tests and upload to docker hub
on: [push]
jobs:

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest Cython
          pip install torch==1.12.1 -f https://download.pytorch.org/whl/cpu
          pip install .

      - name: Run test script
        run: ./tests.sh
        shell: bash
